FROM python:3.14.0-alpine3.21 AS builder

RUN apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    mariadb-dev \
    mariadb-connector-c-dev \
    postgresql-dev \
    libffi-dev \
    openssl-dev \
    zlib-dev \
    jpeg-dev

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.14.0-alpine3.21

WORKDIR /app

COPY requirements.txt /app

RUN apk add --no-cache \
    mariadb-connector-c \
    postgresql-client

COPY --from=builder /install /usr/local

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING="UTF-8" \
    DEBUG=False

RUN django-admin startproject app /app

LABEL org.opencontainers.image.authors="phooshmand@gmail.com"
LABEL org.opencontainers.image.title="Generic Django 5 image"
LABEL org.opencontainers.image.url="https://github.com/peymanhr/django5"
LABEL org.opencontainers.image.source="https://github.com/peymanhr/django5"
LABEL version="1.0"

EXPOSE 80

CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:80"]
