FROM python:3.14.3-alpine3.23 AS builder

RUN apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    mariadb-dev \
    mariadb-connector-c-dev \
    postgresql-dev \
    libffi-dev \
    openssl-dev \
    zlib-dev \
    jpeg-dev

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.14.3-alpine3.23

WORKDIR /app

COPY requirements.txt /app

RUN apk add --no-cache \
    mariadb-connector-c \
    postgresql-client

COPY --from=builder /install /usr/local

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING="UTF-8" \
    DEBUG=False

RUN django-admin startproject app /app

LABEL org.opencontainers.image.authors="phooshmand@gmail.com"
LABEL org.opencontainers.image.title="Generic Django 6 image: apline"
LABEL org.opencontainers.image.url="https://github.com/peymanhr/django6"
LABEL org.opencontainers.image.source="https://github.com/peymanhr/django6"
LABEL version="1.0"

EXPOSE 80

CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:80"]
